script: "bundle exec rake spec"
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  #  TODO: investigate failure
  #- jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
  - ree
gemfile:
  - gemfiles/mongoid2.gemfile
  - Gemfile
notifications:
  recipients:
    - andreas@aloop.org
