sudo: false
before_install:
  - gem update --system
  - gem update bundler
before_script:
  - "bundle exec rake prepare_test_env"
script: "bundle exec rspec"
language: ruby
cache: bundler
services: mongodb
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  #  FIXME: failing native extensions
  #- ruby-head
  #  TODO: investigate failure
  #  This is an arbitrary failure on travis
  #- jruby-19mode
  #- jruby-head
  #- rbx-19mode
gemfile:
  - gemfiles/mongoid2.gemfile
  - gemfiles/mongoid3.gemfile
  - gemfiles/mongoid4.gemfile
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails50.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails51.gemfile

    - rvm: 2.0.0
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails51.gemfile

    - rvm: 2.1.10
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails51.gemfile

    - rvm: 2.4.3
      gemfile: gemfiles/rails3.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails4.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails41.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/mongoid2.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/mongoid3.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/mongoid4.gemfile

    - rvm: 2.5.0
      gemfile: gemfiles/rails3.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails4.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails41.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/mongoid2.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/mongoid3.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/mongoid4.gemfile

notifications:
  recipients:
    - andreas@aloop.org
