before_script:
  - "bundle exec rake prepare_test_env"
script: "bundle exec rspec"
language: ruby
services: mongodb
rvm:
  #- 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.2
  #  FIXME: failing native extensions
  #- ruby-head
  #  TODO: investigate failure
  #  This is an arbitrary failure on travis
  #- jruby-19mode
  #- jruby-head
  #- rbx-19mode
gemfile:
  - gemfiles/mongoid2.gemfile
  - gemfiles/mongoid3.gemfile
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/mongoid3.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails4.gemfile
notifications:
  recipients:
    - andreas@aloop.org
