development:
  clients:
    default:
      database: dummy_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: dummy_test
      hosts:
        - localhost:27017
